---
mqtt:
  topic: '/topic/in/shairport-sync'
  host: raspi  # ideally this is a resolvable hostname (e.g. /etc/host entry)
  port: 1883
  username: null
  password: null
  use_tls: false
  tls:
    ca_certs_path: null
    certfile_path: null
    keyfile_path: null
web_server:
  host: '0.0.0.0'
  port: 8080
  debug: true
  secret_key: 'secrets!'
webui:
  show_player: true
  show_artwork: true
  show_track_metadata: true
  track_metadata:
    - artist
    - album
    - title
    # - genre
  show_update_info: true
# ---
# mqtt:
#   topic: 'shairport-sync/name'
#   host: rpih1  # this should be a resolvable hostname
#   port: 8883
#   use_tls: true
#   tls:
#     ca_certs_path: /path/to/ca_certs  # can be chained.pem or directory
#     certfile_path: client_certificate.crt
#     keyfile_path: key.pem
#     # only for debugging # allow_insecure_server_certificate: false
# web_server:
#   host: '0.0.0.0'
#   port: 8080
#   debug: true
