---
mqtt:
  topic: 'shairport-sync/SS_HOSTNAME'  # there should NOT be a leading slash!
  host: raspimqtt  # a resolvable hostname (e.g. /etc/host entry)
  port: 1883
  username: null
  password: null
  use_tls: false
  tls:
    ca_certs_path: null
    certfile_path: null
    keyfile_path: null
  logger: true

flaschen:
  server: localhost
  port: 1337
  led-rows: 32
  led-columns: 32

# ---
# mqtt:
#   topic: 'shairport-sync/name'
#   host: rpih1  # this should be a resolvable hostname
#   port: 8883
#   use_tls: true
#   tls:
#     ca_certs_path: /path/to/ca_certs  # can be chained.pem or directory
#     certfile_path: client_certificate.crt
#     keyfile_path: key.pem
#     # only for debugging # allow_insecure_server_certificate: false
